### PR TITLE
Clarify ESN bitmap length construction logic

### LINKED ISSUE #323: You have added GPLed code to your library, your license is now incorrect
This line of this commit: https://github.com/vishvananda/netlink/commit/43948793f6d3a2c029b5bd3399d70904b910d668#diff-3a75c4e0509f2a1ae3e9fd2fcc8c6a2fR73

makes your whole library now a GPL library. I hope you realize this. The license file is now incorrect.

### PR DESCRIPTION
**Pull request by aboch**
Closes #323

### CODE REVIEW

**Comment by aboch** [comment]
ping @brb

File: xfrm_state_linux.go [hunk 1]
```diff
@@ -69,8 +69,10 @@ func writeReplayEsn(replayWindow int) []byte {
 		ReplayWindow: uint32(replayWindow),
 	}
 
-	// taken from iproute2/ip/xfrm_state.c:
-	replayEsn.BmpLen = uint32((replayWindow + (4 * 8) - 1) / (4 * 8))
+	// Linux stores the bitmap in blocks of uint32 elements. Therefore bitmap length is the minimum number
+	// of uint32 elements needed to identify the already received sequence packets in the configured window.
+	// The following is basically a ceiling operation.
+	replayEsn.BmpLen = uint32((replayWindow + (sizeof(uint32) * 8) - 1) / (sizeof(uint32) * 8))
```
Comment (aboch) [inline xfrm_state_linux.go]: Context switch from C...

**Comment by brb** [comment]
LGTM
