### PR TITLE
Fix bug in ruleHandle: allocate different buffers for each rtattr

### LINKED ISSUE #150: rule priority defaults to table id value when used with table id higher than 255
I'm trying to set a rule which look like this:
`sudo ip rule add to 200.200.200.200 lookup 500 priority 3000`

produces the following ip rule output:
`3000:  from all to 200.200.200.200 lookup 500`

If the same operation applied with `netlink`:

> _, dstIpNet, _ := net.ParseCIDR("200.200.200.200/32")
> _, srcIpNet, _ := net.ParseCIDR("0.0.0.0/0")
> 
> rule := netlink.NewRule()
> rule.Src = dstIpNet
> rule.Dst = srcIpNet
> rule.Priority = 3000
> rule.Table = 500
> netlink.RuleAdd(rule)`

It produces the following `ip rule` output:
`500:   from 200.200.200.200 lookup 500`

I'm not sure what is the official support status for table ids higher than 255 in the recent kernels? It works fine with CLI and It looks like IDs > 255 work fine in `netlink` if we don't specify the `priority` field. 

I tested it on `3.13.0-76-generic #120-Ubuntu`

Any ideas?

### PR DESCRIPTION
**Pull request by tkojima**
This PR resolves #150.

Here is an example code:

```go
package main

import (
	"fmt"

	"github.com/vishvananda/netlink"
)

func main() {
	rule := netlink.NewRule()

	rule.IifName = "enp4s0"
	rule.Priority = 6789
	rule.Table = 12345

	err := netlink.RuleAdd(rule)

	if err != nil {
		fmt.Println(err)
		return
	}
}
```
 
### before applying the patch

```
% go build -o example
% ./example
0:      from all lookup local 
12345:  from all iif enp4s0 lookup 12345 
32766:  from all lookup main 
32767:  from all lookup default 
```

priority equals to table id.

### after applying the patch

```
% go build -o example
% ./example
0:      from all lookup local 
6789:   from all iif enp4s0 lookup 12345 
32766:  from all lookup main 
32767:  from all lookup default 
```

It seems to work well.

### CODE REVIEW

File: rule_linux.go [hunk 1]
```diff
@@ -82,7 +82,7 @@ func ruleHandle(rule *Rule, req *nl.NetlinkRequest) error {
 		req.AddData(rtAttrs[i])
 	}
 
-	native = nl.NativeEndian()
+	native := nl.NativeEndian()
```
Comment (aboch) [inline rule_linux.go]: This change is part of the previous commit. Same PR.
You do not need an extra commit, just amend the previous one.

Comment (tkojima) [inline rule_linux.go]: OK, I got it.

**Comment by tkojima** [comment]
Thanks for merging!
