### PR TITLE
Link: fix LinkByName with names > 15 chars to use AltNames

### LINKED ISSUE #955: LinkByName with an altname that exceeds the 15 char limit fails
The test for altnames only contains short (<15 char) altnames.
altnames are allowed to carry more characters. See:

```bash
# Query via Name
mava@server01:~/projects$ ip l show dev foobar
22: foobar: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 72:42:33:ae:b7:bf brd ff:ff:ff:ff:ff:ff
    altname some_longer_altname

# Query via long AltName
mava@server01:~/projects$ ip l show dev vx-some_very_long_node_name_l1_e1-1
22: foobar: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 72:42:33:ae:b7:bf brd ff:ff:ff:ff:ff:ff
    altname some_longer_altname
```
However, using this library I am getting the following error:

```bash
mava@server01:~/projects/netlink$ sudo go test -timeout 30s -run ^TestLinkAltName$ github.com/vishvananda/netlink
--- FAIL: TestLinkAltName (0.00s)
    link_test.go:1937: numerical result out of range: Attribute failed policy validation
FAIL
FAIL    github.com/vishvananda/netlink  0.005s
FAIL
```
Find the adjusted test here:
https://github.com/steiler/netlink/commit/32fec641ca0b95078a2e620ba6b17023c0efac02

@SchSeba Maybe you can take a look at this. After implementing #862

### PR DESCRIPTION
**Pull request by steiler**
Fixes  #955.

### CODE REVIEW

File: link_test.go [hunk 1]
```diff
@@ -1899,9 +1899,9 @@ func TestLinkAltName(t *testing.T) {
 		t.Fatal(err)
 	}
 
-	err = LinkAddAltName(link, "altname")
+	err = LinkAddAltName(link, "some_longer_altname")
```
Comment (aboch) [inline link_test.go:1902]: Instead of adding the test code for three alt names can you put them in a slice and have a for loop to test each?

File: link_test.go [hunk 2]
```diff
@@ -1917,29 +1917,29 @@ func TestLinkAltName(t *testing.T) {
...
+		if altName == "some_longer_altname" {
 			altNameExist = true
 		} else if altName == "altname2" {
 			altName2Exist = true
 		}
 
 	}
 	if !altNameExist {
-		t.Fatal("Could not find altname")
+		t.Fatal("Could not find vx-some_longer_altname")
```
[the remark this answers is not in the document]
Comment (steiler) [reply link_test.go]: Sorry, was a remnant of my own testing.
adjusted to  some_longer_altname

File: link_test.go (hunk 1 above)
Comment (steiler) [reply link_test.go]: Are you fine with the new aproach?

File: link_linux.go [hunk 3]
```diff
@@ -1866,8 +1866,13 @@ func (h *Handle) LinkByName(name string) (Link, error) {
...
 	req.AddData(attr)
 
-	nameData := nl.NewRtAttr(unix.IFLA_IFNAME, nl.ZeroTerminated(name))
-	req.AddData(nameData)
+	if len(name) <= 15 {
+		nameData := nl.NewRtAttr(unix.IFLA_IFNAME, nl.ZeroTerminated(name))
+		req.AddData(nameData)
+	} else {
+		nameData := nl.NewRtAttr(unix.IFLA_ALT_IFNAME, nl.ZeroTerminated(name))
+		req.AddData(nameData)
```
Comment (aboch) [inline link_linux.go:1874]: please move this call outside of the if cases

File: link_test.go [hunk 4]
```diff
@@ -1899,64 +1901,56 @@ func TestLinkAltName(t *testing.T) {
...
-	altNameExist := false
-	altName2Exist := false
-	for _, altName := range link.Attrs().AltNames {
-		if altName == "altname" {
-			altNameExist = true
-		} else if altName == "altname2" {
-			altName2Exist = true
-		}
+	sort.Strings(link.Attrs().AltNames)
+	sort.Strings(altNames)
```
Comment (aboch) [inline link_test.go:1919]: can you move this right after the definition of `altNames` ?

File: link_test.go [hunk 5]
```diff
@@ -1899,64 +1901,56 @@ func TestLinkAltName(t *testing.T) {
...
 
-	}
-	if !altNameExist {
-		t.Fatal("Could not find altname")
+	altNamesStr := strings.Join(altNames, ",")
```
Comment (aboch) [inline link_test.go:1921]: Same for this line

File: link_test.go (hunk 1 above)
Comment (aboch) [reply link_test.go]: Yes, thank you.
Can you pls take care of few other very minor comments I added, and most importantly squash your commits into one.
This project follows a "one commit per feature/fix" rule.
Thank you

**Comment by aboch** [comment]
LGTM

File: link_test.go (hunk 4 above)
Comment (steiler) [reply link_test.go]: Done
